version: '3.8'

services:
  betwizz-web:
    build:
      context: .
      dockerfile: Dockerfile
      target: production-stage
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - FLUTTER_WEB=true
    volumes:
      - ./logs:/var/log/nginx
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service
  betwizz-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-stage
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - FLUTTER_WEB=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.dart_tool
    command: flutter run -d web-server --web-port 3000 --web-hostname 0.0.0.0
    profiles:
      - dev

networks:
  default:
    name: betwizz-network
