name: betwizz
description: "A smart betting companion app with AI chat, receipt scanning, and channel management."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  cloud_firestore: ^4.13.6
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # UI & Animations
  cupertino_icons: ^1.0.6
  lottie: ^2.7.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Utilities
  uuid: ^4.2.1
  intl: ^0.19.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  
  # Image & Camera
  image_picker: ^1.0.4
  image: ^4.1.3
  
  # Permissions
  permission_handler: ^11.1.0
  
  # Web specific
  url_launcher: ^6.2.2
  
  # OCR & ML
  google_mlkit_text_recognition: ^0.10.0
  
  # Charts & Analytics
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  
  # Linting
  flutter_lints: ^3.0.0
  
  # Testing
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 700
