name: betwizz
description: "Betwizz - Sports Betting Intelligence Platform for South Africa"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  permission_handler: ^11.0.1
  flutter_local_notifications: ^16.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  uuid: ^4.1.0
  intl: ^0.18.1
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6
  url_launcher: ^6.2.1
  webview_flutter: ^4.4.2
  connectivity_plus: ^5.0.1
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.7
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  image: ^4.1.3
  path_provider: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  agora_rtc_engine: ^6.3.0
  agora_rtm: ^1.5.8
  socket_io_client: ^2.0.3+1
  flutter_dotenv: ^5.1.0
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  lottie: ^2.7.0
  flutter_staggered_grid_view: ^0.7.0
  pull_to_refresh: ^2.0.0
  flutter_slidable: ^3.0.1
  badges: ^3.1.2
  flutter_spinkit: ^5.2.0
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.3.0
  auto_size_text: ^3.0.0
  flutter_html: ^3.0.0-beta.2
  video_player: ^2.8.1
  chewie: ^1.7.4
  flutter_inappwebview: ^6.0.0
  share_plus: ^7.2.1
  flutter_share: ^2.0.0
  screenshot: ^2.1.0
  flutter_colorpicker: ^1.0.3
  flutter_speed_dial: ^7.0.0
  expandable: ^5.0.1
  flutter_markdown: ^0.6.18+2
  markdown: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/animations/
    - assets/config/
    - .env
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/betwizz_logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/betwizz_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/betwizz_logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/betwizz_logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/betwizz_logo.png
  branding: assets/images/betwizz_logo_white.png
  color_dark: "#042a49"
  image_dark: assets/images/betwizz_logo_white.png
  branding_dark: assets/images/betwizz_logo_white.png
  android_12:
    image: assets/images/betwizz_logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/betwizz_logo_white.png
    icon_background_color_dark: "#042a49"
  web: false
