name: betwizz
description: "Sports betting intelligence platform for South Africa with AI-powered predictions and live analysis"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.6
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  
  # Media & Images
  image_picker: ^1.0.5
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  
  # Camera & Scanner
  camera: ^0.10.5+5
  qr_code_scanner: ^1.0.1
  google_ml_kit: ^0.16.0
  
  # Real-time Communication
  socket_io_client: ^2.0.3+1
  web_socket_channel: ^2.4.0
  
  # Payments
  flutter_paystack: ^1.0.7
  
  # Analytics & Performance
  firebase_core: ^2.24.2
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8
  firebase_performance: ^0.9.3+6
  
  # Notifications
  firebase_messaging: ^14.7.6
  flutter_local_notifications: ^16.3.0
  
  # Authentication
  firebase_auth: ^4.15.3
  google_sign_in: ^6.1.6
  
  # Cloud Storage
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  
  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.2
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  path_provider: ^2.1.2
  uuid: ^4.2.1
  
  # Charts & Visualization
  fl_chart: ^1.0.0
  syncfusion_flutter_charts: ^24.1.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/data/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
