name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.0'

    - name: Install Flutter dependencies
      run: flutter pub get

    - name: Analyze Dart code
      run: flutter analyze

    - name: Run Dart tests
      run: flutter test

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install backend dependencies
      run: npm install
      working-directory: ./backend

    - name: Build backend
      run: npm run build
      working-directory: ./backend

    - name: Run backend tests
      run: npm run test
      working-directory: ./backend
